// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ArrowNA.resources {
	
	
	public partial class footer {
		
		protected System.Web.UI.WebControls.Image Image1;
		
		protected System.Web.UI.WebControls.Image Image2;
		
		protected System.Web.UI.WebControls.Image Image3;
	}
}
